#!/bin/bash


N_THREADS='1'
PATH1='/home/t16965tw/github/NPP/analysis/2021-02-01'
PATH2='/home/t16965tw/github/NPP/data/nanopore_16S/BF29'


# pathの設定
echo $(date "+%Y/%m/%d %H:%M:%S") Start program

## 解析ディレクトリのホーム
home_path=$PATH1
echo $home_path

## シークエンスデータのパス
dir_path=$PATH2
echo $dir_path

## fastqファイルの結合
PREFIX=$(basename $dir_path)
mkdir $PREFIX
cd $PREFIX
cat $dir_path/*.fastq > $PREFIX.fastq

# サンプルQC
echo $(date "+%Y/%m/%d %H:%M:%S") Start QC
## アダプターのトリミング
porechop -i $PREFIX.fastq -o $PREFIX.porechop.fastq

## リードのstatisticsの取得
NanoStat --fastq $PREFIX.porechop.fastq

## Nanoplotでクオリティとリード長の分布
NanoPlot --fastq $PREFIX.porechop.fastq --loglength -t $N_THREADS -o qc_result -f pdf

## クオリティフィルタリング
cat $PREFIX.porechop.fastq |NanoFilt -q 10 -l 1200 --maxlength 1800 > $PREFIX.trimmed.porechop.fastq

## Nanoplotでクオリティとリード長の分布
NanoPlot --fastq $PREFIX.trimmed.porechop.fastq --loglength -t $N_THREADS -o qc_result_trimmed -f pdf

## fasta形式に変換
awk '(NR - 1) % 4 < 2' $PREFIX.trimmed.porechop.fastq | sed 's/@/>/' > $PREFIX.trimmed.porechop.fasta


# リード数の調整
echo $(date "+%Y/%m/%d %H:%M:%S") Start QC
# 10万配列以上ある場合にはランダムサンプリングする
L_NUM=$(cat $PREFIX.trimmed.porechop.fasta| awk 'END{print NR}')
if [ $L_NUM -ge 400000 ]; then
  echo $(date "+%Y/%m/%d %H:%M:%S") Start Random sampling
  seqkit sample -n 100000 $PREFIX.trimmed.porechop.fasta > $PREFIX.trimmed.porechop_.fasta
else
  cat $PREFIX.trimmed.porechop.fasta > $PREFIX.trimmed.porechop_.fasta
  echo $(date "+%Y/%m/%d %H:%M:%S") Numbers of reads is under 100000
fi

echo $(date "+%Y/%m/%d %H:%M:%S") Done

