#!/bin/bash


# pathの設定

## 解析ディレクトリのホーム
home_path=$(cd $(dirname $0);pwd)
echo `$home_path`
echo $home_path

## シークエンスデータのパス
dir_path=$1
echo `$dir_path`
echo $dir_path



# 解析データセットの準備

## 解析ディレクトリの作成
DIR_NAME=$(date +%F_%H%M%S)
mkdir $DIR_NAME
cd $DIR_NAME

## fastqファイルの結合
PREFIX=$(basename$dir_path)
mkdir $PREFIX
cd $PREFIX
cat $dir_path/*.fastq > $PREFIX.fastq

# サンプルQC

## アダプターのトリミング
porechop -i all.fastq -o all.porechop.fastq

# リードのstatisticsの取得
NanoStat --fastq all.porechop.fastq -t $N_THREADS

# Nanoplotでクオリティとリード長の分布
NanoPlot --fastq all.porechop.fastq --loglength -t $N_THREADS -o qc_result -f pdf

# クオリティフィルタリング
# 5'末端50-bpのトリミング、平均クオリティ10以下のリードを捨てるクオリティフィルタリング、500bp以下のリードを捨てる
cat all.porechop.fastq |NanoFilt -q 10 -l 500 --headcrop 75 > all.trimmed.porechop.fastq

# Nanoplotでクオリティとリード長の分布
NanoPlot --fastq all.trimmed.porechop.fastq --loglength -t $N_THREADS -o qc_result_trimmed -f pdf

