#PBS -q smps
#PBS -l ncpus=20
#PBS -l mem=450G
#PBS -V

cd ${PBS_O_WORKDIR}

# ファイルパスの設定

FASTQ='fastq'
N_THREADS='20'
METADATA='/home/t16965tw/github/NPP/data/metadata/2020-03-16_B_metadata.txt'
DATABASE='/home/t16965tw/data/qiime2_silva/SILVA-v138-515f-806r-classifier.qza'

qiime feature-classifier classify-sklearn \
--p-n-jobs -$N_THREADS \
--i-classifier $DATABASE \
--i-reads rep-seqs.qza \
--o-classification taxonomy.qza

qiime metadata tabulate \
--m-input-file taxonomy.qza \
--o-visualization taxonomy.qzv

qiime taxa barplot \
--i-table table.qza \
--i-taxonomy taxonomy.qza \
--m-metadata-file $METADATA \
--o-visualization taxa-bar-plots.qzv

qiime tools export \
  --input-path table.qza \
  --output-path exported-feature-table.biom

cd exported-feature-table.biom/
biom convert --to-tsv -i feature-table.biom -o table.tsv
