#PBS -q small
#PBS -l ncpus=1
#PBS -l mem=95G
#PBS -V

cd ${PBS_O_WORKDIR}

# ファイルパスの設定
FASTQ='/home/t16965tw/data/metagenome/202004-06-01-2/fastq'

# FASTQファイルのインポート
qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  --input-path $FASTQ \
  --input-format CasavaOneEightSingleLanePerSampleDirFmt \
  --output-path demux.qza

qiime demux summarize \
--i-data demux.qza \
--o-visualization demux.qzv
